#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/utils.sh

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 <path/to/source>"
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp $TMPDIR/kubernetes-resource-request.XXXXXX)

cat > $payload <&0

server=$(jq -r '.source.server // ""' < "$payload")
token=$(jq -r '.source.token // ""' < "$payload")
namespace=$(jq -r '.source.namespace // ""' < "$payload")
cert=$(jq -r '.source.cert // ""' < "$payload")

manifests=$(jq -r '.params.manifests // ""' < "$payload")


log "source: $source"
log "server: $server"
log "token: $token"
log "namespace $namespace"
log "cert $cert"

log "manifests $manifests"

timestamp="$(jq -n "{version:{timestamp:\"$(date +%s)\"}}")"
echo "$timestamp" | jq -s add  >&3
